feat(): layout management list
Teradata/covalent-markdown-navigator-nightly pull request #27
Opened 2019-03-25 14:55 UTC by joejcarey

## Description
moved the layout management list into it's own branch for review 

### What's included?
- Management list layout and route

#### Test Steps
- [ ] Management list - confirm the nav view is displaying properly. 

##### Screenshots

#### Management list
<img width="913" alt="Screen Shot 2019-03-25 at 9 54 04 AM" src="https://user-images.githubusercontent.com/34658520/54929662-f109ba00-4ee3-11e9-89d8-0b39fb6a4d08.png">

2019-03-25 16:43 UTC, jennmedellin approved these changes
UX LGTM

2019-04-02 03:35 UTC, feldominguez requested changes
Linting good now! Some unnecessary code needs to get deleted and we're good.

2019-04-02 03:35 UTC, philgetz commented on src/app/layouts/manage-list/manage-list.component.html
> +      <mat-toolbar-row>
No need for mat-toolbar-row here. mat-toolbar-row is only used with multi-row mat-toolbar.

2019-04-02 03:35 UTC, philgetz commented on src/app/layouts/manage-list/manage-list.component.html
> +      <mat-toolbar-row>
Same here no need for mat-toolbar-row

2019-04-02 03:35 UTC, philgetz commented on src/app/layouts/manage-list/manage-list.component.html
> +        <div td-toolbar-content layout="row" layout-align="start center" flex>
td-toolbar-content directive unnecessary here since we are within a mat-toolbar component.

2019-04-02 03:35 UTC, philgetz commented on src/app/layouts/manage-list/manage-list.component.html
> +      <mat-divider></mat-divider>
Left over mat-divider? No need for it here.

2019-06-20 23:32 UTC, JulieMarie approved these changes
Code LGTM

2019-06-20 23:38 UTC, merged