feat(): layout nav list
Teradata/covalent-markdown-navigator-nightly pull request #28
Opened 2019-03-25 15:02 UTC by joejcarey

## Description
moved the layout nav list into it's own branch for review 

### What's included?
- Nav list layout and route

#### Test Steps
- [ ] Nav List - confirm the nav view is displaying properly. 

##### Screenshots

#### Nav List
<img width="913" alt="Screen Shot 2019-03-25 at 10 02 16 AM" src="https://user-images.githubusercontent.com/34658520/54930336-19de7f00-4ee5-11e9-8044-0f77f6f07b5e.png">

2019-03-25 16:34 UTC, jennmedellin approved these changes
UX LGTM

2019-04-02 03:14 UTC, feldominguez requested changes
Linting is good now, just the extra divs on that card and we're good.

2019-04-02 03:14 UTC, philgetz commented on src/app/layouts/nav-list/nav-list.component.html
> +      </div>
No need for the extra 2 divs wrapping mat-card-title and subtitle. Same for the span.

2019-06-20 23:03 UTC, JulieMarie approved these changes
Code LGTM

2019-06-20 23:09 UTC, merged